            - name: ServiceNow DevOps Change
  # You may pin to the exact commit or the version.
  # uses: rapdev-io/sn-devops-change@d81ab3123ec5da61f1f2d92d5b3661d9e0d66f35
  uses: rapdev-io/sn-devops-change@v2.0.1
  with:
    # DevOps Integration User Name
    devops-integration-user-name: 
    # DevOps Integration User Pass
    devops-integration-user-pass: 
    # ServiceNow Instance Name (e.g.: rapdevio)
    instance-name: 
    # Orchestration tool id
    tool-id: 
    # Github context
    context-github: 
    # Callback repo
    callback-repo: 
    # Callback pipeline ID
    callback-pipeline-id: 
    # Callback params
    callback-params: 
          
